version: "3.3"
services:
  #  linkding:
  #    image: sissbruecker/linkding
  #    restart: unless-stopped
  #    volumes:
  #      - linkding_data:/etc/linkding/data
  #    ports:
  #      - 9090:9090

  linkding-oidc:
    image: sissbruecker/linkding
    restart: unless-stopped
    volumes:
      - linkding_data:/etc/linkding/data
    ports:
      - 9901:9090
    environment:
      - OIDC_RP_CLIENT_ID=${CLIENT_ID}
      - OIDC_RP_CLIENT_SECRET=${CLIENT_SECRET}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${AUTH_ENDPOINT}
      - OIDC_OP_TOKEN_ENDPOINT=${TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${USER_ENDPOINT}
      - OIDC_RP_SIGN_ALGO=${SIGN_ALGO}
      - OIDC_OP_JWKS_ENDPOINT=${JWKS_ENDPOINT}
      - LD_ENABLE_OIDC=True

  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    ports:
      - 9902:8080
    networks:
      - db_db

    environment:
      - DEFAULT_DOMAIN=link.nighmared.ch
      - IS_HTTPS_ENABLED=false
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - DB_DRIVER=postgres
      - DB_USER=${SH_DB_USER}
      - DB_PASSWORD=${SH_DB_PASS}
      - DB_HOST=${SH_DB_HOST}
  shlink-web:
    image: shlinkio/shlink-web-client
    ports:
      - 9903:8080

volumes:
  linkding_data:

networks:
  db_db:
    external: true
