version: "3.3"
services:
  linkding:
    image: sissbruecker/linkding
    restart: unless-stopped
    volumes:
      - linkding_data:/etc/linkding/data
    ports:
      - 9090:9090


volumes:
  linkding_data:

