version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: unless-stopped
    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 3001:3001
    volumes:
      - kuma-config:/app/data

volumes:
  kuma-config:

networks:
  media:
    external: true
