version: "3.3"
services:
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - radarr_config:/config
      - ${MOVIES_DIR}:/movies
      - ${MCU_DIR}:/mcu
      - ${BOND_DIR}:/bond
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - sonarr_config:/config
      - ${SERIES_DIR}:/tv
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet

  readarr:
    image: linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - readarr_config:/config
      - ${BOOKS_DIR}:/books
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet
  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - bazarr_config:/config
      - ${SERIES_DIR}:/tv
      - ${MOVIES_DIR}:/movies
      - ${BOND_DIR}:/bond
      - ${MCU_DIR}:/mcu
  prowlarr:
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - prowlarr_config:/config

  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      - media
    dns:
      - ${LOCAL_DNS_IP}
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ombi_config:/config
  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    networks:
      - media
    dns:
      - ${LOCAL_DNS_IP}
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - overseerr_config:/app/config

  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - deluge_config:/config
      - ${SERIES_DIR}:/tv
      - ${MOVIES_DIR}:/movies
      - ${MCU_DIR}:/mcu
      - ${BOND_DIR}:/bond
      - ${DOWNLOADS_DIR}:/torrents

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission_config:/config
      - ${DOWNLOADS_DIR}:/torrents
      - ${MCU_DIR}:/mcu
      - ${SERIES_DIR}:/tv
      - ${BOND_DIR}:/bond
      - ${MOVIES_DIR}:/movies
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 6789:6789
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - nzbget_config:/config
      - ${DOWNLOADS_DIR_USENET}:/usenet
      - ${MCU_DIR}:/mcu
      - ${SERIES_DIR}:/tv
      - ${BOND_DIR}:/bond
      - ${MOVIES_DIR}:/movies

  kavita:
    image: kizaing/kavita:latest
    networks:
      - media
      - kavita
    volumes:
      - ${BOOKS_DIR}:/books
      - kavita_config:/kavita/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - 5000:5000
    restart: unless-stopped
  kavita-email:
    image: kizaing/kavitaemail:latest
    restart: unless-stopped
    networks:
      - kavita
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - SMTP_HOST=${KAVITA_EMAIL_SMTP_HOST}
      - SMTP_PORT=${KAVITA_EMAIL_SMTP_PORT}
      - SMTP_USER=${KAVITA_EMAIL_SMTP_USER}
      - SMTP_PASS=${KAVITA_EMAIL_SMTP_PASS}
      - SEND_ADDR=${KAVITA_EMAIL_SEND_ADDR}
      - DISP_NAME=${KAVITA_EMAIL_DISP_NAME}
      - ALLOW_SENDTO=true
  plex-meta-manager:
    image: meisnate12/plex-meta-manager:latest
    restart: unless-stopped

    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    environment:
      # - PMM_RADARR_API=${RADARR_API_KEY}
      # - PMM_SONARR_API=${SONARR_API_KEY}
      - PMM_PLEX_TOKEN=${PMM_PLEX_TOKEN}
      - PMM_TMDB_API=${TMDB_API_KEY}
    volumes:
      - ./plex-meta-manager/config:/config:rw
    command: ["python", "./plex-meta-manager.py", "--run"]

volumes:
  radarr_config:
  sonarr_config:
  readarr_config:
  bazarr_config:
  prowlarr_config:
  ombi_config:
  overseerr_config:
  deluge_config:
  transmission_config:
  nzbget_config:
  kavita_config:

networks:
  media: null
  kavita: null
