version: "3.3"
services:
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - radarr_config:/config
      - ${MOVIES_DIR}:/movies
      - ${MCU_DIR}:/mcu
      - ${BOND_DIR}:/bond
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 192.168.1.11
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - sonarr_config:/config
      - ${SERIES_DIR}:/tv
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet

  readarr:
    image: linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - readarr_config:/config
      - ${BOOKS_DIR}:/books
      - ${DOWNLOADS_DIR}:/torrents
      - ${DOWNLOADS_DIR_USENET}:/usenet
  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - bazarr_config:/config
      - ${SERIES_DIR}:/tv
      - ${MOVIES_DIR}:/movies
      - ${BOND_DIR}:/bond
      - ${MCU_DIR}:/mcu
  prowlarr:
    image: linuxserver/prowlarr:nightly
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - prowlarr_config:/config

  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    networks:
      - media
    dns:
      - ${LOCAL_DNS_IP}
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ombi_config:/config
  overseerr:
    image: linuxserver/overseerr
    restart: unless-stopped
    networks:
      - media
    dns:
      - ${LOCAL_DNS_IP}
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - overseerr_config:/config

  deluge:
    image: linuxserver/deluge
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - deluge_config:/config
      - ${SERIES_DIR}:/tv
      - ${MOVIES_DIR}:/movies
      - ${MCU_DIR}:/mcu
      - ${BOND_DIR}:/bond
      - ${DOWNLOADS_DIR}:/torrents

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission_config:/config
      - ${DOWNLOADS_DIR}:/torrents
      - ${MCU_DIR}:/mcu
      - ${SERIES_DIR}:/tv
      - ${BOND_DIR}:/bond
      - ${MOVIES_DIR}:/movies
  nzbget:
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    networks:
      - media
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 6789:6789
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - NZBGET_USER=${NZBGET_USER}
      - NZBGET_PASS=${NZBGET_PASS}
    volumes:
      - nzbget_config:/config
      - ${DOWNLOADS_DIR_USENET}:/usenet
      - ${MCU_DIR}:/mcu
      - ${SERIES_DIR}:/tv
      - ${BOND_DIR}:/bond
      - ${MOVIES_DIR}:/movies

  kavita:
    image: kizaing/kavita:latest
    networks:
      - media
      - kavita
    volumes:
      - ${BOOKS_DIR}:/books
      - kavita_config:/kavita/config
    environment:
      - TZ=Europe/Berlin
    ports:
      - 5000:5000
    restart: unless-stopped
  kavita-email:
    image: kizaing/kavitaemail:latest
    restart: unless-stopped
    networks:
      - kavita
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - SMTP_HOST=${KAVITA_EMAIL_SMTP_HOST}
      - SMTP_PORT=${KAVITA_EMAIL_SMTP_PORT}
      - SMTP_USER=${KAVITA_EMAIL_SMTP_USER}
      - SMTP_PASS=${KAVITA_EMAIL_SMTP_PASS}
      - SEND_ADDR=${KAVITA_EMAIL_SEND_ADDR}
      - DISP_NAME=${KAVITA_EMAIL_DISP_NAME}
      - ALLOW_SENDTO=true
  
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=root
    volumes:
      - tdarr_server:/app/server
      - tdarr_config:/app/configs
      - tdarr_logs:/app/logs
      - tdarr_transcode_cache:/temp
      - ${MCU_DIR}:/media/MCU
      - ${BOND_DIR}:/media/bond
      - ${SERIES_DIR}:/media/series
      - ${MOVIES_DIR}:/media/movies


volumes:
  radarr_config:
  sonarr_config:
  readarr_config:
  bazarr_config:
  prowlarr_config:
  ombi_config:
  overseerr_config:
  deluge_config:
  transmission_config:
  nzbget_config:
  kavita_config:
  tdarr_server:
  tdarr_config:
  tdarr_logs:
  tdarr_transcode_cache:

networks:
  media: null
  kavita: null
