version: "3.3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    restart: unless-stopped
    networks:
      - keycloak
      - db_db
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    environment:
      - KEYCLOAK_ADMIN=${ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KC_DB=${DB_TYPE}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_URL=${DB_URL}
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HEALTH_ENABLED=true

    command: ["start"]
networks:
  keycloak:
    driver: bridge
  db_db:
    external: true
