version: "3.3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    restart: unless-stopped
    networks:
      - keycloak
      - db_db
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=${ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KC_DB=${DB_TYPE}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_URL_HOST=${DB_HOST}
      - KC_DB_URL_DATABASE=${DB_DB_NAME}

    command: ["start-dev"]
networks:
  keycloak: null
  db_db:
    external: true
