version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - paperless

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "9800:8000"
    networks:
      - db_db
      - paperless
    volumes:
      - ${PAPERLESS_CONSUME_DIR}:/usr/src/paperless/consume
      - ${PAPERLESS_DATA_DIR}:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_DIR}:/usr/src/paperless/media
      - ${PAPERLESS_EXPORT_DIR}:/usr/src/paperless/export
    environment:
      - PAPERLESS_REDIS=redis://paperless-ngx-broker-1:6379
      - PAPERLESS_DBHOST=${DB_HOST}
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=${PAPERLESS_DBPASS}
      #- PAPERLESS_DBENGINE=postgresql # default value is postgres
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=htt://paperless-ngx-gotenberg-1:3000
      - PAPERLESS_TIKA_ENDPOINT=http://paperless-ngx-tika-1:9998
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_URL=${PAPERLESS_URL}
      - PAPERLESS_ADMIN_USER=admin
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_TASK_WORKERS=2
      - PAPERLESS_TIME_ZONE=CET
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
      # - PAPERLESS_APPS="allauth.socialaccount.providers.openid_connect"
      - 'PAPERLESS_OCR_USER_ARGS={"invalidate_digital_signatures": true}'

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    networks:
      - paperless

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    networks:
      - paperless

volumes:
  redis_data:

networks:
  db_db:
    external: true
  paperless:
    driver: bridge
