version: "3.3"
services:
  syncthing:
    image: syncthing/syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${SHARE_DIR}/${WHOAMI}/recordings:/recordings
      - syncthing_config:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp #tcp file transfers
      - 22000:22000/udp #quic file transfers
      - 21027:21027/udp #receive local discovery broadcasts
  sftpgo:
#    image: drakkan/sftpgo:v2
    build: .
    restart: unless-stopped
    networks:
      - keycloak_keycloak
    ports:
      - 8090:8090
      - 2022:2022
      - 51414:51414
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - sftpgo_config:/var/lib/sftpgo
      - ${CONFIG_MOUNTPOINT}:/etc/sftpgo
      - ${SHARE_DIR}:/srv/sftpgo



volumes:
  sftpgo_config:
  syncthing_config:
networks:
  keycloak_keycloak:
    external: true
