services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - 81:81
      - 9990:9990
      - ${public_http}:80
      - ${public_https}:443
    volumes:
      - proxy_manager_data:/data
      - proxy_manager_letsencrypt:/etc/letsencrypt

volumes:
  proxy_manager_data:
  proxy_manager_letsencrypt:
