version: "3.3"
services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:${DB_PASSWORD}
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_DB:default
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  db: null
